server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        formal_sql: true
        show_sql: true
    open-in-view: false
